# Import necessary libraries
import os
from dotenv import load_dotenv
import discord
from discord.ext import commands
from datetime import datetime
from datetime import time as dtime
from apscheduler.triggers.cron import CronTrigger
from apscheduler.schedulers.asyncio import AsyncIOScheduler
import pandas as pd
import pytz
from scraper.scraper import runScraper

# Bot initialization
intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)
load_dotenv()

# Load environment variables
DISCORD_TOKEN =      os.getenv("DISCORD_TOKEN")
DISCORD_CHANNEL_ID = os.getenv("CHANNEL_ID")
LOCAL_TZ =           os.getenv("LOCAL_TZ")
SEND_HOUR =          os.getenv("SEND_HOUR")
SEND_MIN =           os.getenv("SEND_MIN")

# Convert environment variable types to integers after logging
DISCORD_CHANNEL_ID = int(DISCORD_CHANNEL_ID) if DISCORD_CHANNEL_ID is not None else None
SEND_HOUR =          int(SEND_HOUR) if SEND_HOUR is not None else None
SEND_MIN =           int(SEND_MIN) if SEND_MIN is not None else None

# Helper function to create all needed current time formats
def getTimeContext(SEND_HOUR, SEND_MIN, LOCAL_TZ: str):
    """
    Get current time context in various formats.

    Captures the current moment and returns a dictionary of formatted strings 
    and objects to ensure consistency across the entire script.

    Args:
        LOCAL_TZ (str): Local timezone string.

    Returns:
        dictionary {
            utcSendTime (dtime): Time object in UTC for scheduling.
            dateFileStr (str): Date string for file name to locate (e.g., '2024-09-10').
            displayDateStr (str): Date string for data filter and display in embed (e.g., 'Sep 10').
        }
    """
    # Create a UTC time zone object based on send time environment variables
    utcSendTime = convertToUtc(SEND_HOUR, SEND_MIN, LOCAL_TZ)

    # Build date string for today's date file
    dateFileStr = datetime.now().strftime("%Y-%m-%d")

    # Build display date string for data filtering and embed 
    displayDateStr = datetime.now().strftime("%b %d")

    return {
        "utcSendTime": utcSendTime,
        "dateFileStr": dateFileStr,
        "displayDateStr": displayDateStr
    }

# Helper function to convert local time to UTC
def convertToUtc(hour: int, minute: int, localTimeZoneString: str = LOCAL_TZ) -> tuple:
    """
    Convert local time to UTC time.

    Args:
        hour (int): Hour in local time (24-hour format).
        minute (int): Minute in local time.
        localTimeZoneString (str): Local timezone string.

    Returns:
        utcDateTime (datetime): Corresponding UTC datetime object.

    """
    # TODO: Anaylze code performance and redundancy
    localTimeZone = pytz.timezone(localTimeZoneString)
    now = datetime.now(localTimeZone)
    localDateTime = localTimeZone.localize(datetime(now.year, now.month, now.day, hour, minute))
    utcDateTime = localDateTime.astimezone(pytz.utc)
    return utcDateTime

# Function to process news file and generate DataFrame
def processNewsFile():
    """
    Process the news CSV file for today's date.

    Reads the CSV file generated by the scraper, filters relevant news based on 
    currency and impact.

    Returns:
        pd.DataFrame: Filtered news data for today.
    """
    # Build file path for today's news CSV
    fileStr = timeContext['dateFileStr'] + '_news.csv'
    news_path = os.path.join(os.path.abspath("news"), fileStr)

    # Check if file exists
    if not os.path.exists(news_path):
        print(f"[WARN] File not found: {news_path}")
        return pd.DataFrame() # Return empty DF if file is missing

    # Read and filter news data
    news = pd.read_csv(news_path)

    # Filtering logic by currency and impact
    news = news[news['currency'] == 'USD']
    news = news[news['impact'].isin(['red', 'orange'])]

    # Use the date from our context instead of calling datetime.now() again
    rows_to_display = news[news['date'] == timeContext['displayDateStr']]


# # TODO: Split into smaller functions and modularize
# async def sendDailyMessage():
    
    

#         # Build embed description
#         if rowsToDisplay.empty:
#             desc = "No relevant news today"
#             color = 0x808080 # Grey for no news
#         else:
#             desc = ""
#             for _, row in rowsToDisplay.iterrows():
#                 # Set color to red if any red impact
#                 if row['impact'] == 'red':
#                     color = 0xFF0000
#                 elif row['impact'] == 'orange' and color != 0xFF0000:
#                     color = 0xFFA500
#                 elif row['impact'] == 'yellow' and color not in (0xFF0000, 0xFFA500):
#                     color = 0xFFFF00
#                 desc += f"`{row['time']}` **{row['currency']}** {row['impact'].capitalize()} - {row['event']}\n"
#         embed = discord.Embed(title=f"{todayDisplay} News", description=desc, color=color)
#         embed.set_footer(text="Source: Forex Factory\nhttps://www.forexfactory.com/")
#     print(f"[INFO] Attempting to get channel with ID: {DISCORD_CHANNEL_ID}")
#     channel = bot.get_channel(DISCORD_CHANNEL_ID)
#     if channel:
#         print("[INFO] Channel found, sending embed...")
#         await channel.send(embed=embed)
#         print('[INFO] Embed sent successfully')
#     else:
#         print("[ERROR] Channel not found! Check channel ID and bot permissions.")

#     # Cleanup: delete today's CSV after sending message
#     try:
#         from scraper.cleanup import delete_today_csv
#         delete_today_csv()
#     except Exception as e:
#         print(f"[CLEANUP] Error during CSV deletion: {e}")

# Get time context
timeContext = getTimeContext(SEND_HOUR, SEND_MIN, LOCAL_TZ)

# Schedule daily scrape and message sending job
@bot.event
async def on_ready():
    """
    Event handler when the bot is ready.

    Sets up the scheduler to send daily messages at the specified UTC time.
    """
    sendTime = timeContext['utcSendTime']
    scheduler = AsyncIOScheduler()
    scheduler.add_job(sendDailyMessage, 'cron', hour=sendTime.hour, minute=sendTime.minute)
    scheduler.start()

# Scrape news data
runScraper()

# Process news file
processNewsFile()

# Build embed
def buildEmbed():

# Send embed to channel
async def sendEmbedToChannel():
bot.run(DISCORD_TOKEN)

# Clean up old files